### PR TITLE
Time to break more fucking shit 

### PR DESCRIPTION
**Pull request by EFHDev**
Does stuff, like in a bad way

### CODE REVIEW

**Review by EFHDev — COMMENTED** [review]
This needs checked, for some reason, on my end, suddenly stopped loading everything except discordRPC.

**Comment by EFHDev** [comment]
(app.js that is)

**Comment by Nehaxfr** [comment]
missing await keyword when calling `startServer()`

**Review by Nehaxfr — CHANGES_REQUESTED** [review]
add `await` keyword to `startServer()` function calls

**Review by Nehaxfr — CHANGES_REQUESTED** [review]
rename the `startServer()` function to something else (`initializeApp()` ?) to avoid confusion with the one in `Server`

**Review by Nehaxfr — APPROVED** [review]

**Pull request closed without merging**
