### PR TITLE
Client scripts generation

### PR DESCRIPTION
**Pull request by yopgaming**
Hello,
I have added a feature to generate client scripts in order to separate client from server. 

Settings page : choice to select default start or client scripts
Start Tarkov : 
 - default : runs Tarkov through exec() as before
 - script : generate a zip archive containing required scripts for running Tarkov on the remote server

Best regards

### CODE REVIEW

**Comment by EFHDev** [comment]
Heya!, we have a archiver in Depends already, can you switch to use ``node-7z-archive createArchive`` when zipping up the files?

**Comment by yopgaming** [comment]
Hello,
I will do the switch to `node-7z-archive`.

**Comment by SlejmUr** [comment]
My personal preference is not store anything inside the account.json that doesn't belong there.
My other is make a webinterface as a mod but thats me. I don't think king would be happy with that.

**Comment by Nehaxfr** [comment]
Thank you for your contribution, if you plan on working more on MTGA and wish to join the discord, send me a message or add me on discord: Nehax#5682

**Comment by yopgaming** [comment]
Thanks for your feedbacks.

**Pull request merged**
